name: Hydroseal
favicon: null
layout_spectrum: 0.8328168555162847
typography_spectrum: 0.9727895553223789
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.81044708378613
  lightness: 0.4425083016976714
  saturation: 0.11769921635277569
  rhythmicContrast: 0.6917679198086262
purpose: []
