name: Hydroseal
favicon: null
layout_spectrum: 1
typography_spectrum: 0.46027
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#121617'
    - '#ad2800'
    - '#7e9296'
    - '#fa6b57'
  brandStrength: 0.81044708378613
  lightness: 0.4425083016976714
  saturation: 0.375
  rhythmicContrast: 0.6917679198086262
purpose: []
